server:
  port: 7070

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  #    defer-datasource-initialization: true
  #    properties.hibernate.format_sql: true
  data:
    rest:
      basePath: '/api'
  graphql:
    graphiql:
      enabled: true
